// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBum8jyamgaUDrdk4Kxl3z-k7HVoT4n714',
    appId: '1:321192723603:web:7b0596c36866efbd8fb966',
    messagingSenderId: '321192723603',
    projectId: 'sih-2025-83f30',
    authDomain: 'sih-2025-83f30.firebaseapp.com',
    storageBucket: 'sih-2025-83f30.firebasestorage.app',
    measurementId: 'G-4XMH6G2MNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtqqjtvUjSNnOTQW_MNszyYn9xSP8zts0',
    appId: '1:321192723603:android:41b49a4d74c76e1c8fb966',
    messagingSenderId: '321192723603',
    projectId: 'sih-2025-83f30',
    storageBucket: 'sih-2025-83f30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANz84s8lccq865--XsT_hJz-Oafm3RpfM',
    appId: '1:321192723603:ios:912aa765e1fe15278fb966',
    messagingSenderId: '321192723603',
    projectId: 'sih-2025-83f30',
    storageBucket: 'sih-2025-83f30.firebasestorage.app',
    iosClientId: '321192723603-lus8crg6vabkcqvcgphi70e16pkhu6q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.sihNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANz84s8lccq865--XsT_hJz-Oafm3RpfM',
    appId: '1:321192723603:ios:912aa765e1fe15278fb966',
    messagingSenderId: '321192723603',
    projectId: 'sih-2025-83f30',
    storageBucket: 'sih-2025-83f30.firebasestorage.app',
    iosClientId: '321192723603-lus8crg6vabkcqvcgphi70e16pkhu6q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.sihNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBum8jyamgaUDrdk4Kxl3z-k7HVoT4n714',
    appId: '1:321192723603:web:085ad593806dacca8fb966',
    messagingSenderId: '321192723603',
    projectId: 'sih-2025-83f30',
    authDomain: 'sih-2025-83f30.firebaseapp.com',
    storageBucket: 'sih-2025-83f30.firebasestorage.app',
    measurementId: 'G-HXFQGWZBW0',
  );

}